version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - rust

  - package-ecosystem: npm
    directory: /packages/travsr-vscode
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript

  - package-ecosystem: npm
    directory: /packages/travsr-lsif-ts
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript
    groups:
      typescript-compiler:
        patterns:
          - "typescript"
        update-types:
          - "patch"
          - "minor"
          - "major"
    reviewers:
      - raj-rkv

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - ci
