#!/usr/bin/env bash
# Regenerate plugin-hashes.lock after bumping plugin_version.
set -euo pipefail

LOCK_FILE="plugin-hashes.lock"
CRATES_DIR="crates"

echo "# Auto-generated by update-plugin-hashes.sh — do not edit manually" > "$LOCK_FILE"
echo "# Format: crate_name = sha256_of_src_tree" >> "$LOCK_FILE"
echo "" >> "$LOCK_FILE"

for src_dir in "$CRATES_DIR"/travsr-plugin-*/src; do
    crate=$(basename "$(dirname "$src_dir")")
    hash=$(find "$src_dir" -type f -name "*.rs" | sort | xargs sha256sum 2>/dev/null | sha256sum | awk '{print $1}')
    echo "$crate = $hash" >> "$LOCK_FILE"
    echo "Updated: $crate = ${hash:0:16}..."
done

echo "Done. Commit $LOCK_FILE."
