#!/usr/bin/env bash
# Regenerate plugin-hashes.lock after bumping plugin_version.
set -euo pipefail

LOCK_FILE="plugin-hashes.lock"
CRATES_DIR="crates"

# Portable SHA-256: prefer sha256sum (GNU coreutils / Linux), fall back to
# shasum -a 256 (macOS / BSD). Fail loudly if neither is available.
if command -v sha256sum &>/dev/null; then
    SHA256=sha256sum
elif command -v shasum &>/dev/null; then
    SHA256="shasum -a 256"
else
    echo "ERROR: neither sha256sum nor shasum found on PATH" >&2
    exit 1
fi

# Write to a temp file and atomically replace, so an interrupted run never
# leaves a partially-written lock file that breaks the next CI check.
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

{
    echo "# Auto-generated by update-plugin-hashes.sh — do not edit manually"
    echo "# Format: crate_name = sha256_of_src_tree"
    echo ""

    for src_dir in "$CRATES_DIR"/travsr-plugin-*/src; do
        crate=$(basename "$(dirname "$src_dir")")
        # Hash file contents only (not paths) so the hash is identical across macOS and Linux.
        # Use a while-read loop instead of xargs to avoid xargs reading from stdin when find
        # produces no output (which hangs on GNU xargs or produces wrong hash on BSD).
        # LC_ALL=C pins byte-order collation so the generated hash does not depend on the
        # contributor's shell locale; see the matching comment in check-plugin-hashes.sh.
        # Must stay identical to the `sort` there or this script emits a lock file that
        # gate immediately rejects.
        hash=$(find "$src_dir" -type f -name "*.rs" | LC_ALL=C sort | while IFS= read -r f; do cat -- "$f"; done | $SHA256 | awk '{print $1}')
        echo "$crate = $hash"
        echo "Updated: $crate = ${hash:0:16}..." >&2
    done
} > "$TMP"

mv "$TMP" "$LOCK_FILE"
echo "Done. Commit $LOCK_FILE."
