pub mod c;
mod convert;
pub mod cpp;
pub mod csharp;
pub mod dart;
pub mod generic;
pub mod go;
pub mod java;
pub mod kotlin;
pub mod objc;
pub mod php;
pub mod python;
pub mod ruby;
pub mod rust;
pub mod scala;
pub mod swift;
pub mod typescript;
pub use convert::{parse_output_to_response, response_to_output};
