-- RFC-027 section 12: record what the live lane actually claimed, so its
-- precision can be measured against Phase B's answer at the next commit.
--
-- The edge itself cannot answer this. By the time ratification runs, a live edge
-- Phase B re-derived has already been relabelled in place, and one it did not
-- re-derive is about to be swept. Either way the edges table no longer says
-- "the live lane resolved this reference to this node" — only that a row exists,
-- or does not. This column is that claim, kept independently of the edge's fate.
--
-- NULL for a pending row: an abstention resolved to nothing, which is the whole
-- point of it.
ALTER TABLE ref_resolution_state ADD COLUMN resolved_dst INTEGER;
